### ISSUE TITLE
Hospitalized: Missing/Duplicate Dates?

### ISSUE THREAD

**Issue by xrisfg** [thecityny/covid-19-nyc-data#2]
In [hospitalized.csv](https://github.com/thecityny/covid-19-nyc-data/blob/master/hospitalized.csv):

- May 6th row is missing
- May 5th and 7th have the same data
- May 8th is the last date

**Comment by willcwelch** [comment]
The city has been less consistent recently in their responses to our requests for this data. They've given us duplicate data a few times, which was the also the case on 4/18. We removed the row for 5/7 so that we're handling those the same way. 

Data availability now consistently lags the recorded date by 3-7 days. We are generally getting things in batches, which are sometimes missing days. We're doing our best to fill the gaps, but numbers may not be available for every day.
